plannerapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("users.urls"))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.home, name='home'),
    path('logout/', views.logout_view, name='logout_view'),
    path('map/', views.map, name='map'),
    path('form/', views.submit_preferences, name='form'),
    path('new_location/', views.submit_review, name='submit_review'),
    path('admin_approve_location/', views.admin_approve_reviews, name='admin_approve_reviews'),
    path('admin_approve_admin/', views.admin_approve_admin, name='admin_approve_admin'),
    path("itinerary/", views.display_itinerary, name='itinerary'),
    path("all_locations/", views.all_locations, name='all_locations'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    is_admin_user = models.BooleanField(default=False)


class ActivityLocation(models.Model):
    name = models.CharField(max_length=255)
    activity_type = models.CharField(
        max_length=50,
        choices=[
            ('outdoor', 'Outdoor'),
            ('indoor', 'Indoor'),
            ('educational', 'Educational'),
        ],
        default='outdoor'
    )
    latitude = models.FloatField()
    longitude = models.FloatField()
    approved = models.BooleanField(default=False)

    @property
    def location_type_display(self):
        return 'activity'

    def __str__(self):
        return self.name


class RestaurantLocation(models.Model):
    name = models.CharField(max_length=255)
    restaurant_type = models.CharField(
        max_length=50,
        choices=[
            ('Chinese', 'Chinese'),
            ('Italian', 'Italian'),
            ('Japanese', 'Japanese'),
            ('French', 'French'),
            ('American', 'American'),
            ('Indian', 'Indian'),
            ('Middle-Eastern', 'Middle-Eastern'),
        ]
    )
    latitude = models.FloatField()
    longitude = models.FloatField()
    approved = models.BooleanField(default=False)

    @property
    def location_type_display(self):
        return 'restaurant'
    def __str__(self):
        return self.name


class GasStationLocation(models.Model):
    name = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    approved = models.BooleanField(default=False)

    @property
    def location_type_display(self):
        return 'gas_station'

    def __str__(self):
        return self.name


class UserPreferences(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=False)
    time_start = models.TimeField(auto_now_add=False)
    time_end = models.TimeField(auto_now_add=False)
    activity_type = models.CharField(
        max_length=50,
        choices=[
            ('outdoor', 'Outdoor'),
            ('indoor', 'Indoor'),
            ('educational', 'Educational'),
        ],
        default='outdoor'
    )
    restaurant_style = models.CharField(
        max_length=50,
        choices=[
            ('Chinese', 'Chinese'),
            ('Italian', 'Italian'),
            ('Japanese', 'Japanese'),
            ('French', 'French'),
            ('American', 'American'),
            ('Indian', 'Indian'),
            ('Middle-Eastern', 'Middle-Eastern'),
            ('Spanish', 'Spanish')
        ],
        default='Chinese'
    )

    def __str__(self):
        return f"Preferences for {self.user.username}"


class Itinerary(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField #and this?
    activity = models.ForeignKey(ActivityLocation, related_name='itinerary_activities', on_delete=models.CASCADE)
    restaurant = models.ForeignKey(RestaurantLocation, related_name='itinerary_restaurants', on_delete=models.CASCADE)
    gas_station = models.ForeignKey(GasStationLocation, related_name='itinerary_gas_station', on_delete=models.CASCADE)
    activity_duration_hours = models.PositiveIntegerField(default=1)
    activity_duration_minutes = models.PositiveIntegerField(default=0)
    restaurant_duration_hours = models.PositiveIntegerField(default=1)
    restaurant_duration_minutes = models.PositiveIntegerField(default=0)
    gas_station_duration_minutes = models.PositiveIntegerField(default=15)

    def __str__(self):
        return f"Itinerary for {self.user.username}"

users/forms.py
from django import forms
from django.forms import TimeInput, DateInput

from .models import UserPreferences
from django.utils import timezone


class UserPreferencesForm(forms.ModelForm):
    class Meta:
        model = UserPreferences
        fields = ['date', 'time_start', 'time_end', 'activity_type', 'restaurant_style']

    def clean_date(self):
        date = self.cleaned_data['date']

        if date < timezone.now().date():
            raise forms.ValidationError("Date must be today or in the future.")

        return date

    def clean(self):
        cleaned_data = super().clean()
        time_start = cleaned_data.get('time_start')
        time_end = cleaned_data.get('time_end')

        if time_start and time_end and time_start >= time_end:
            raise forms.ValidationError("End time must be after start time.")

    date = forms.DateField(
        widget=DateInput(attrs={'type': 'date'}))
    time_start = forms.TimeField(
        widget=TimeInput(attrs={'type': 'time'}))
    time_end = forms.TimeField(
        widget=TimeInput(attrs={'type': 'time'}))

    ACTIVITY_CHOICES = [
        ('outdoor', 'Outdoor'),
        ('indoor', 'Indoor'),
        ('educational', 'Educational'),
    ]
    activity_type = forms.ChoiceField(
        choices=ACTIVITY_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    RESTAURANT_CHOICES = [
        ('Chinese', 'Chinese'),
        ('Italian', 'Italian'),
        ('Japanese', 'Japanese'),
        ('French', 'French'),
        ('American', 'American'),
        ('Indian', 'Indian'),
        ('Middle-Eastern', 'Middle-Eastern'),
    ]
    restaurant_style = forms.ChoiceField(
        choices=RESTAURANT_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class NewAdminForm(forms.Form):
    user_email = forms.CharField(
        max_length=500,
        label="User's email",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

# Add a search functionality
# Add a filter functionality
ORDER_CHOICES = [
    ('asc', 'Ascending'),
    ('desc', 'Descending')
]


class ReviewSearchForm(forms.Form):
    SEARCH_FIELDS = (
        ('place__name', 'Place Name'),
        ('review', 'Review'),
        ('rating', 'Rating'),
    )

    search_field = forms.ChoiceField(choices=SEARCH_FIELDS, widget=forms.Select(), required=True)
    search_query = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search...'}), required=True)

    filter_by = forms.ChoiceField(choices=[
        ('created_at', 'Posted Date'),
        ('rating', 'Rating'),
    ], required=False, label="Filter by")

    order = forms.ChoiceField(choices=ORDER_CHOICES, required=False, label="Order")


class NewLocationForm(forms.Form):
    LOCATION_TYPE_CHOICES = [
        ('activity', 'Activity'),
        ('restaurant', 'Restaurant'),
    ]
    ACTIVITY_TYPE_CHOICES = [
        ('outdoor', 'Outdoor'),
        ('indoor', 'Indoor'),
        ('educational', 'Educational'),
    ]

    RESTAURANT_TYPE_CHOICES = [
        ('Chinese', 'Chinese'),
        ('Italian', 'Italian'),
        ('Japanese', 'Japanese'),
        ('French', 'French'),
        ('American', 'American'),
        ('Indian', 'Indian'),
        ('Middle-Eastern', 'Middle-Eastern'),
    ]

    name = forms.CharField(label='Location Name', max_length=255)
    location_type = forms.ChoiceField(label='Location Type', choices=LOCATION_TYPE_CHOICES)
    activity_type = forms.ChoiceField(label='Activity Type', choices=ACTIVITY_TYPE_CHOICES, required=False)
    restaurant_type = forms.ChoiceField(label='Restaurant Type', choices=RESTAURANT_TYPE_CHOICES, required=False)
    latitude = forms.FloatField(widget=forms.HiddenInput())
    longitude = forms.FloatField(widget=forms.HiddenInput())

users/templates/admin_approve_admin.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>

    <title>Welcome User Page</title>

    <style>
        .logo {
            max-width: 400px;
        }
    </style>

</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow justify-content-between">
        <img class="logo" src="{% static 'users/images/logo.png' %}" alt="Logo">
        <div>
            <a class="btn btn-outline-dark" href="{% url 'users:home' %}">Home</a>
            <a class="btn btn-outline-dark" href="{% url 'users:admin_approve_reviews' %}">Approve New Locations</a>
            <a class="btn btn-outline-danger ml-3" href="{% url 'users:logout_view' %}">Logout</a>
        </div>
    </div>

    <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
        <div class="card p-4">
            <h2 class="text-center">Add New Admin User</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-3">
                        <label for="{{ form.user_email.id_for_label }}"></label>
                        {{ form }}
                    </div>
                </div>
                <div class="centered-button">
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
            </form>
            {% for message in messages %}
                <div class="alert alert-success mt-3">
                    <a class="close" href="#" data-dismiss="alert">×</a>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>


</body>

</html>

users/templates/all_locations.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>

    <title>All Reviews</title>

    <style>
        .logo {
            max-width: 400px;
        }
    </style>
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow justify-content-between">
        <img class="logo" src="{% static 'users/images/logo.png' %}" alt="Logo">
        <div>
            <a class="btn btn-outline-dark" href="{% url 'users:home' %}">Home</a>
            <a class="btn btn-outline-dark" href="{% url 'users:map' %}">Map</a>
            <a class="btn btn-outline-dark" href="{% url 'users:submit_review' %}">Propose New Location</a>
            <a class="btn btn-outline-dark" href="{% url 'users:form' %}">Create Itinerary</a>
            <a class="btn btn-outline-danger ml-3" href="{% url 'users:logout_view' %}">Logout</a>
        </div>
    </div>

<div class="container mt-5">

        <form method="get" action="{% url 'users:all_locations' %}">
            <div class="row mb-3">
                <div class="col-md-3">
                    <label for="filter_by" class="form-label">Filter By:</label>
                    <select name="filter_by" id="filter_by" class="form-select">
                        <option value="" disabled selected hidden>Select</option>
                        <option>All</option>
                        <option value="activity">Activities</option>
                        <option value="restaurant">Restaurants</option>
                        <option value="gas_station">Gas Stations</option>
                    </select>
                </div>

                <div class="col-md-3">
                    <label for="order" class="form-label">Alphabetical Order:</label>
                    <select name="order" id="order" class="form-select">
                        <option value="" disabled selected hidden>Select</option>
                        <option value="asc">Ascending</option>
                        <option value="desc">Descending</option>
                    </select>
                </div>

                <div class="col-md-12 mt-3">
                    <button type="submit" class="btn btn-outline-primary">Apply Filters</button>
                </div>
            </div>
        </form>

        <div class="border p-4">
            <div class="border-bottom mb-3">
                <h1>All Activities</h1>
            </div>
            {% for activity in activity_locations %}
                <div class="mb-4">
                    <h3>{{ activity.name }}</h3>
                    <p>Type: {{ activity.activity_type }}</p>
                    <p>Latitude: {{ activity.latitude }}</p>
                    <p>Longitude: {{ activity.longitude }}</p>
                    <p class="text-end"><strong>Approved:</strong> {% if activity.approved %}Yes{% else %}No{% endif %}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        <div class="border p-4 mt-4">
            <div class="border-bottom mb-3">
                <h1>All Restaurants</h1>
            </div>
            {% for restaurant in restaurant_locations %}
                <div class="mb-4">
                    <h3>{{ restaurant.name }}</h3>
                    <p>Type: {{ restaurant.restaurant_type }}</p>
                    <p>Latitude: {{ restaurant.latitude }}</p>
                    <p>Longitude: {{ restaurant.longitude }}</p>
                    <p class="text-end"><strong>Approved:</strong> {% if restaurant.approved %}Yes{% else %}No{% endif %}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>

        <div class="border p-4 mt-4">
            <div class="border-bottom mb-3">
                <h1>All Gas Stations</h1>
            </div>
            {% for gas_station in gas_station_locations %}
                <div class="mb-4">
                    <h3>{{ gas_station.name }}</h3>
                    <p>Latitude: {{ gas_station.latitude }}</p>
                    <p>Longitude: {{ gas_station.longitude }}</p>
                    <p class="text-end"><strong>Approved:</strong> {% if gas_station.approved %}Yes{% else %}No{% endif %}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>

</div>
</body>

</html>

users/templates/create_itinerary.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>

    <title>Welcome User Page</title>

    <style>
        .logo {
            max-width: 400px;
        }
        .centered-button {
            text-align: center;
            margin-top: 20px;
        }

        .centered-button button {
            padding: 10px 20px;
        }

        .custom-spacing label {
            display: block;
        }
    </style>

</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow justify-content-between">
        <img class="logo" src="{% static 'users/images/logo.png' %}" alt="Logo">
        <div>
            <a class="btn btn-outline-dark" href="{% url 'users:home' %}">Home</a>
            <a class="btn btn-outline-dark" href="{% url 'users:map' %}">Map</a>
            <a class="btn btn-outline-dark" href="{% url 'users:submit_review' %}">Propose New Location</a>
            <a class="btn btn-outline-dark" href="{% url 'users:all_locations' %}">All Locations</a>
            <a class="btn btn-outline-danger ml-3" href="{% url 'users:logout_view' %}">Logout</a>
        </div>
    </div>
<div class="container mt-5">
    <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
        <div class="card p-5">
            <h2 class="text-center">Submit Preferences</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group custom-spacing">
                    <label for="{{ form.date.id_for_label }}">Date</label>
                    {{ form.date }}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="{{ form.time_start.id_for_label }}">Start Time</label>
                        {{ form.time_start }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="{{ form.time_end.id_for_label }}">End Time</label>
                        {{ form.time_end }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.activity_type.id_for_label }}">Activity Type</label>
                    {{ form.activity_type }}
                </div>
                <div class="form-group">
                    <label for="{{ form.restaurant_style.id_for_label }}">Restaurant Style</label>
                    {{ form.restaurant_style }}
                </div>

                <div class="centered-button">
                    <button type="submit" class="btn btn-outline-primary">Submit Preferences</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% if error_messages %}
    <script>
        alert("Errors:\n\n{% for message in error_messages %}{{ message }}\n{% endfor %}");
    </script>
{% endif %}

</body>
</html>

users/templates/itinerary.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>

    <title>Welcome User Page</title>

    <style>
        .logo {
            max-width: 400px;
        }
    </style>

</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow justify-content-between">
        <img class="logo" src="{% static 'users/images/logo.png' %}" alt="Logo">
        <div>
            <a class="btn btn-outline-dark" href="{% url 'users:home' %}">Home</a>
            <a class="btn btn-outline-dark" href="{% url 'users:map' %}">Map</a>
            <a class="btn btn-outline-dark" href="{% url 'users:submit_review' %}">Propose New Location</a>
            <a class="btn btn-outline-dark" href="{% url 'users:all_locations' %}">All Locations</a>
            <a class="btn btn-outline-danger ml-3" href="{% url 'users:logout_view' %}">Logout</a>
        </div>
    </div>
    <div class="container mt-5">
    <div class="d-flex justify-content-center align-items-center" style="min-height: 70vh;">
        <div class="card p-5">
            <h2 class="text-center">{{ user.first_name }}'s Itinerary</h2>

                <p><strong>Activity:</strong> {{ itinerary.activity.name }}</p>
                <p><strong>Restaurant:</strong> {{ itinerary.restaurant.name }}</p>
                <p><strong>Gas Station:</strong> {{ itinerary.gas_station.name }}</p>
                <p><strong>Activity Duration:</strong> {{ itinerary.activity_duration_hours }} hours and {{ itinerary.activity_duration_minutes }} minutes</p>
                <p><strong>Restaurant Duration:</strong> {{ itinerary.restaurant_duration_hours }} hours and {{ itinerary.restaurant_duration_minutes }} minutes</p>
                <p><strong>Gas Station Duration:</strong> {{ itinerary.gas_station_duration_minutes }} minutes</p>

                <a class="btn btn-outline-primary ml-3" href="{% url 'users:map' %}">View Itinerary Map</a>

        </div>
    </div>
    </div>
</body>

</html>

users/templates/new_location_form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
         integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
           integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
           crossorigin="anonymous">
   </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

   <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
   <link rel="stylesheet" href="{% static 'users/style.css' %}">

   <title>Propose New Location</title>

   <style>
       .logo {
           max-width: 400px;
       }
       .centered-button {
           text-align: center;
           margin-top: 20px;
       }
       .centered-button button {
           padding: 10px 20px;
       }
       #map {
           height: 400px;
           width: 100%;
       }
   </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow justify-content-between">
   <img class="logo" src="{% static 'users/images/logo.png' %}" alt="Logo">
   <div>
        <a class="btn btn-outline-dark" href="{% url 'users:home' %}">Home</a>
        <a class="btn btn-outline-dark" href="{% url 'users:map' %}">Map</a>
        <a class="btn btn-outline-dark" href="{% url 'users:form' %}">Create Itinerary</a>
        <a class="btn btn-outline-dark" href="{% url 'users:all_locations' %}">All Locations</a>
        <a class="btn btn-outline-danger ml-3" href="{% url 'users:logout_view' %}">Logout</a>
   </div>
</div>

<div class="container-fluid mt-5">
    <div class="row justify-content-center align-items-center" style="min-height: 70vh;">
        <div class="col-12 col-lg-10">
            <div class="card p-4">
                <h2 class="text-center">Propose New Location</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Location Name</label>
                        <input type="text" class="form-control" id="id_name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="id_location_type">Location Type</label>
                        <select class="form-control" id="id_location_type" name="location_type">
                            <option value="" disabled selected hidden>Select Location Type</option>
                            <option value="activity">Activity</option>
                            <option value="restaurant">Restaurant</option>
                        </select>
                    </div>
                    <div class="form-group" id="activity_type_field" style="display: none;">
                        <label for="id_activity_type">Activity Type</label>
                        <select class="form-control" id="id_activity_type" name="activity_type">
                            <option value="" disabled selected hidden>Select Activity Type</option>
                            <option value="outdoor">Outdoor</option>
                            <option value="indoor">Indoor</option>
                            <option value="educational">Educational</option>
                        </select>
                    </div>
                    <div class="form-group" id="restaurant_type_field" style="display: none;">
                        <label for="id_restaurant_type">Restaurant Type</label>
                        <select class="form-control" id="id_restaurant_type" name="restaurant_type">
                            <option value="" disabled selected hidden>Select Restaurant Type</option>
                            <option value="Chinese">Chinese</option>
                            <option value="Italian">Italian</option>
                            <option value="Japanese">Japanese</option>
                            <option value="French">French</option>
                            <option value="American">American</option>
                            <option value="Indian">Indian</option>
                            <option value="Middle-Eastern">Middle-Eastern</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Click on the Map to Select Location</label>
                        <div id="map"></div>
                    </div>
                    <input type="hidden" name="latitude" id="latitude">
                    <input type="hidden" name="longitude" id="longitude">
                    <div class="centered-button">
                        <button type="submit" class="btn btn-outline-primary ml-3">Submit Proposition</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
// show/hide activity_type and restaurant_type fields based on location_type
$(document).ready(function () {
    var locationTypeField = $('#id_location_type');
    var activityTypeField = $('#activity_type_field');
    var restaurantTypeField = $('#restaurant_type_field');

    locationTypeField.on('change', function () {
        var selectedLocationType = locationTypeField.val();
        if (selectedLocationType === 'activity') {
            activityTypeField.show();
            restaurantTypeField.hide();
        } else if (selectedLocationType === 'restaurant') {
            activityTypeField.hide();
            restaurantTypeField.show();
        } else {
            activityTypeField.hide();
            restaurantTypeField.hide();
        }
    });
});
</script>

<!-- Google Maps Script -->
<script>
function initMap() {
    // Coordinates for Charlottesville
    const charlottesville = { lat: 38.0293, lng: -78.4767 };
    const map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: charlottesville,
    });

    let marker;

    {#Used ChatGPT for help with figuring out the marker logic#}
    map.addListener('click', (e) => {
        // Remove the previous marker if it exists
        if (marker) {
            marker.setMap(null);
        }
        // Place a new marker
        marker = new google.maps.Marker({
            position: e.latLng,
            map: map,
        });

        // Update hidden form fields
        document.getElementById('latitude').value = e.latLng.lat();
        document.getElementById('longitude').value = e.latLng.lng();
    });
}

// Load the map script dynamically
function loadMapScript() {
    let script = document.createElement('script');
    script.src = 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCIgCa4b0DzRT4UA8C-N8WTWafJdgZeB5s&callback=initMap';
    script.defer = true;
    script.async = true;
    document.head.appendChild(script);
}

window.onload = loadMapScript;
</script>